
language: node_js
node_js: '4.0'

notifications:
  email: false

before_install:
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
install:
  - npm install -g firebase-tools
  - npm install .

before_script:
  - npm run prepublish

script: npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
  - master
  
sudo: false # route your build to the container-based infrastructure for a faster